version: '3'
services:
  db:
    image: postgres:13.1-alpine
    container_name: nasa-apod-telegram-db
    environment:
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "POSTGRES_DB=postgres"
    env_file:
        - ./.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - nasa-apod-telegram-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nasa-apod-telegram-network
  bot:
    build:
      context: .
    container_name: nasa-apod-telegram-go
    image: nasa-apod-telegram-go
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - nasa-apod-telegram-network
    depends_on:
      - db
  

volumes:
  nasa-apod-telegram-db-volume:
    driver: local

networks:
  nasa-apod-telegram-network:
    driver: bridge